.\" Copyright (C) 2007 Sven Arvidsson <sa@whiz.se>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH five-or-more 6 "2007\-06\-06" "GNOME"
.SH NAME
Five or More \- GNOME port of the once-popular Colour Lines game
.SH SYNOPSIS
.B five-or-more
.RI [ OPTION... ]
.SH DESCRIPTION
.B five-or-more
is the GNOME port of the once popular Windows game called Colour Lines.
The game's objective is to align as often as possible five or more
objects of the same colour and shape causing them to disappear.
.SH OPTIONS
This program only accepts the standard GNOME and GTK options.
.SH AUTHORS
.B five-or-more
was written by Robert Szokovacs <szo@szo.hu> and
Szabolcs Ban <shooby@gnome.hu>.
.P
This manual page was written by Sven Arvidsson <sa@whiz.se>,
for the Debian project (but may be used by others).
.SH SEE ALSO
.BR "gtk-options" (7),
.BR "gnome-options" (7)
.P
The online documentation available through the program's
.I Help
menu.
